---
title: "INST 314: Statistics for Information Science"
---

# What's on this site

Welcome! If you are registered for the 2025 Summer II session of INST 314 (section 21) at the University of Maryland, with Scott Jackson as your instructor, you are in the right place.

This is where I am hosting the main instructional mnaterials including:

- The weekly *readings* for each Unit, including practice Knowledge Checks.
- The weekly *code tutorials* for each Unit.

Other materials like the Practice exercises, weekly Challenges, data files, etc. are available on the official course site on ELMS.

# How to use this site

- The navigation is mainly on the left-hand side. The selections are grouped, so there is an item for each Unit, but then under each Unit there is a *Concepts Reading*, and then a set of *Code Tutorials*. The latter are broken into multiple files as well.
- Once you're on a page, there should be a list of sections on the right hand side to help you navigate to specific topics. I'm hoping this is helpful when you want to return to a section for review.
- All of these materials are intended to be read through from beginning to end (though of course you can take breaks). If you try to skip around and read sections out of order, it might not make as much sense.
- I will be adding material and additional resources as we go through the course, so this is still a work in progress.
- There's a little toggle in the upper right if you want to switch between light and dark color schemes.

# Code and Code Tutorials

- This site is created using [Quarto](https://quarto.org/), which means the pages are mostly written in a flavor of [R Markdown](https://rmarkdown.rstudio.com/).
- This also means there will be sections of code and results, especially in the Code Tutorials.
- You should be running all of the code yoruself on your own machine as you work through the material.
- You can either copy & paste the code from this site, or you can just download the `.qmd` source files, either by cloning this entire repository off of GitHub, or by visiting the course site on ELMS and downloading them from the *Modules* section of that site.
