<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The t distribution, computing p-values, and constructing confidence intervals. – INST 314 (Summer 2025)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5f8498b817ae5b2cb3a7a87727a6ad5f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-2c7af7b2a4cbf6e016b7c3feffc32b4a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed slimcontent quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">INST 314 (Summer 2025)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_reading.html">Unit 5: Making Inferences</a></li><li class="breadcrumb-item"><a href="./R_t_distribution_confidence.html">Code Tutorials</a></li><li class="breadcrumb-item"><a href="./R_t_distribution_confidence.html">Working with t-values, p-values, and confidence intervals</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Preliminaries</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./installing_R_RStudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installing R and RStudio</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unit 1: Starting with the Basics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_basics_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Reading: some basic data concepts</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Code Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_basics_fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting started with R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_basics_vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vectors: a basic building block of data in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_basics_dataframes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Frames: the most useful data structure in R</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unit 2: Univariate Distributions</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./univariate_distributions_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Reading: univariate distributions</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Code Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_basics_packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using R packages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_univariate_distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulating, visualizing, and exploring univariate distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Applying transformations</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Unit 3: Fitting Regression Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression_foundations_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Reading: linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Code Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_scatterplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizing relationships with scatterplots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_lm_fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting linear models with the <code>lm()</code> function</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_boxplots_violinplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualizing differences with boxplots and violinplots</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_advanced_data_formatting_PearsonLee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Example of some advanced data formatting (optional)</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Unit 4: Examining Errors and Evaluating Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./errors_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Reading: errors in regression models</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Code Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Examining model residuals in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_modelsimulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simulating data from a model in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_modelstats.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extracting model fit statistics in R</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Unit 5: Making Inferences</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts Reading: uncertainty and hypothesis testing</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Code Tutorials</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_t_distribution_confidence.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Working with t-values, p-values, and confidence intervals</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_regression_inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extracting inferences from model fits</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#whats-in-this-tutorial" id="toc-whats-in-this-tutorial" class="nav-link active" data-scroll-target="#whats-in-this-tutorial">What’s in this tutorial?</a></li>
  <li><a href="#loading-data-and-packages" id="toc-loading-data-and-packages" class="nav-link" data-scroll-target="#loading-data-and-packages">Loading data and packages</a></li>
  <li><a href="#the-t-distribution" id="toc-the-t-distribution" class="nav-link" data-scroll-target="#the-t-distribution">The <em>t</em> distribution</a>
  <ul class="collapse">
  <li><a href="#visualizing-the-distribution" id="toc-visualizing-the-distribution" class="nav-link" data-scroll-target="#visualizing-the-distribution">Visualizing the distribution</a>
  <ul class="collapse">
  <li><a href="#densities" id="toc-densities" class="nav-link" data-scroll-target="#densities">Densities</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom">Degrees of freedom</a></li>
  <li><a href="#plotting" id="toc-plotting" class="nav-link" data-scroll-target="#plotting">Plotting</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#calculating-a-p-value-from-a-t-distribution" id="toc-calculating-a-p-value-from-a-t-distribution" class="nav-link" data-scroll-target="#calculating-a-p-value-from-a-t-distribution">Calculating a <em>p</em> value from a <em>t</em> distribution</a>
  <ul class="collapse">
  <li><a href="#populations-and-samples" id="toc-populations-and-samples" class="nav-link" data-scroll-target="#populations-and-samples">Populations and samples</a></li>
  <li><a href="#computing-standard-errors-and-t-values" id="toc-computing-standard-errors-and-t-values" class="nav-link" data-scroll-target="#computing-standard-errors-and-t-values">Computing standard errors and <em>t</em> values</a></li>
  <li><a href="#testing-the-t" id="toc-testing-the-t" class="nav-link" data-scroll-target="#testing-the-t">Testing the <em>t</em></a></li>
  <li><a href="#regression-coefficient-tests" id="toc-regression-coefficient-tests" class="nav-link" data-scroll-target="#regression-coefficient-tests">Regression coefficient tests</a></li>
  </ul></li>
  <li><a href="#constructing-a-confidence-interval" id="toc-constructing-a-confidence-interval" class="nav-link" data-scroll-target="#constructing-a-confidence-interval">Constructing a confidence interval</a>
  <ul class="collapse">
  <li><a href="#confidence-intervals-for-regression-parameters" id="toc-confidence-intervals-for-regression-parameters" class="nav-link" data-scroll-target="#confidence-intervals-for-regression-parameters">Confidence intervals for regression parameters</a></li>
  <li><a href="#other-confidence-intervals" id="toc-other-confidence-intervals" class="nav-link" data-scroll-target="#other-confidence-intervals">Other confidence intervals</a></li>
  <li><a href="#quick-and-dirty-confidence" id="toc-quick-and-dirty-confidence" class="nav-link" data-scroll-target="#quick-and-dirty-confidence">Quick and dirty confidence</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inference_reading.html">Unit 5: Making Inferences</a></li><li class="breadcrumb-item"><a href="./R_t_distribution_confidence.html">Code Tutorials</a></li><li class="breadcrumb-item"><a href="./R_t_distribution_confidence.html">Working with t-values, p-values, and confidence intervals</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">The t distribution, computing p-values, and constructing confidence intervals.</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="whats-in-this-tutorial" class="level1">
<h1>What’s in this tutorial?</h1>
<p>This tutorial walks through some of the calculations and code related to a few topics. First, we will examine the <em>t</em> distribution in a bit more detail. I mentioned <em>t</em> values in the <a href="./inference_reading.html">Unit 5 reading</a>, as an example of a <em>test statistic</em>, but I did not explain much about it. We will fill in those gaps here.</p>
<p>The <em>t</em> value is an important distribution, especially for NHST, and we will go through how <em>p</em>-values are computed from this distribution.</p>
<p>Finally, we will combine these topics together in order to show how to construct a precise <em>confidence interval</em> around an estimate.</p>
<p>I recommend going through the <a href="./inference_reading.html">Unit 5 reading</a> before going through this tutorial, in order to get more background on these concepts and their uses.</p>
</section>
<section id="loading-data-and-packages" class="level1">
<h1>Loading data and packages</h1>
<p>We will once again use the Pearson &amp; Lee (1908) data on the heights of fathers and their sons, and we will use the <code>ggplot2</code> package for some graphs. Finally, we will also use the <code>dplyr</code> and <code>tidyr</code> packages for some data manipulation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>pl <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"FatherSonHeights.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-t-distribution" class="level1 page-columns page-full">
<h1>The <em>t</em> distribution</h1>
<p>Our initial focus in <a href="./univariate_distributions_reading.html">Unit 2</a> was on the uniform and normal (Gaussian) distributions. However, these are just a few of many important and useful distributions that have been described and formulated by statisticians.</p>
<p>One of the most important is the <em>t</em> distribution.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Here is a run down of some of the highlights of this distribution:</p>
<div class="no-row-height column-margin column-container"><div id="fn1"><p><sup>1</sup>&nbsp;This is sometimes called the “Student’s <em>t</em>”, and there’s a fun bit of trivia about that name. The originator of the <em>t</em> distribution and the <em>t-test</em> was a statistician named William Gosset, whose day job was to work as a brewer and chemist for the Guinness beer company at the beginning of the 20th century. He developed these concepts as a way for Guinness to improve their brewing processes. But this was a “high tech” advancement at the time, and Guinness did not want to risk tipping off their competitors that they were using such advanced mathematical techniques to improve their beer. So Gosset had to publish much of his influential work under a pseudonym, “Student.”</p></div></div><ul>
<li>The <em>t</em> distribution has just a single parameter: <em>degrees of freedom</em>, which has to be a positive number (and is usually an integer).</li>
<li>The distribution is very similar to a <em>standard normal</em> distribution, but with thicker “tails”, meaning that extreme values that are farther from the central values are more common in the <em>t</em> than in a normal.</li>
<li>As the degrees of freedom get larger, the closer the distribution resembles a <em>standard normal</em> distribution.</li>
<li>The distribution is a good description of the difference between two sample means.</li>
<li>The distribution is used to assess statistical significance in regression parameters.</li>
</ul>
<section id="visualizing-the-distribution" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-distribution">Visualizing the distribution</h2>
<p>In order to illustrate a few of these points, let’s visualize what the distribution looks like, by changing the degrees of freedom, and comparing these to a standard normal distribution.</p>
<section id="densities" class="level3">
<h3 class="anchored" data-anchor-id="densities">Densities</h3>
<p>First, just as we used <code>dnorm()</code> to calculate densities for values from normal distributions, we can use <code>dt()</code> to do the same for the <em>t</em> distribution. One difference is that while we needed to provide both a mean and standard deviation for the normal distribution, all we need for a <em>t</em> distribution is the <em>degrees of freedom</em> parameter.</p>
<p>The following code starts by creating a bunch of values from -4 to 4, and then uses the <code>dt()</code> function to calculate the corresponding <em>t</em>-distribution densities, for a few different values of degrees of freedom (1, 2, 4, and 10).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>x_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, .<span class="dv">05</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>t_01 <span class="ot">&lt;-</span> <span class="fu">dt</span>(x_vals, <span class="dv">1</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>t_02 <span class="ot">&lt;-</span> <span class="fu">dt</span>(x_vals, <span class="dv">2</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>t_04 <span class="ot">&lt;-</span> <span class="fu">dt</span>(x_vals, <span class="dv">4</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>t_10 <span class="ot">&lt;-</span> <span class="fu">dt</span>(x_vals, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will visualize these below, after doing a little work to make the graph prettier.</p>
</section>
<section id="degrees-of-freedom" class="level3">
<h3 class="anchored" data-anchor-id="degrees-of-freedom">Degrees of freedom</h3>
<p>But first, what’s a “degree of freedom”? This is a concept that comes up in other places in statistics, so it’s worth spending a little time on. Let’s imagine that we are talking about estimating a mean for a set of values. And let’s say that we play a guessing game, where we both know the mean, but we don’t yet know the values we are averaging. My job is to make up values, and my only rule is that by the time I finish listing the numbers, they have to average out to the mean that we already know. Your job is to try to guess each of the numbers that I pick. How well do you think you could do?</p>
<p>As an example, imagine that we know that the mean is 10. For the first number, you have essentially no chance at guessing, because I could pick literally any number. I have total <em>freedom</em> in determining a value. So I’ll just pick -3,742.933. Bet you couldn’t have guessed that! But now, if you just do a little math, you know exactly what the next number will be, because my hands are tied. I <em>have</em> to pick 3,762.933 if the mean value is already determined to be 10.</p>
<p>Now imagine that we play the game again, and we still set the mean to be 10, but now I have 100 numbers to pick. How many do you think you could get? After thinking about for a bit, you should come to the conclusion that for the first 99 numbers, I have total freedom, and there’s almost zero chance of you reading my mind to multiple decimal numbers. But again, once we get to that final number, as long as you do the math, you have a 100% chance of guessing correctly, because we both know what the final mean value is.</p>
<p>In statistical terms, this situation describes how I have a very simple model with one parameter, namely the mean. And so I end up having <em>degrees of freedom</em> (the freedom to be able to pick any number I want) equal to the total number of data points, minus one. As we have more complex models with more parameters, those parameters each “spend” a degree of freedom.</p>
<p>If you think about a simple regression, it has two parameters: the intercept and slope. And if there are only two <em>data</em> points, there can’t be any “noise” in the model because just having two points defines the line exactly. There are no degrees of freedom left! Similarly, if we have three data points in a regression, then there’s just one degree of freedom left, because if we both know the slope and intercept, I could pick a point anywhere I wanted in coordinate space for the first point, but then I wouldn’t have any choice about where to put the last two points in order to make the regression line fit the target intercept and slope.</p>
<p>This pattern continues as we have models with more parameters. Therefore, the general formula (most of the time) is that the degrees of freedom parameter is calculated as <span class="math inline">\(N\)</span>, the number of data points, minus <span class="math inline">\(k\)</span>, the number of parameters.</p>
<p>Bringing this back to the <em>t</em> distribution, this means that as we get more data, the degrees of freedom will also increase, and as the degrees of freedom increase, the <em>t</em> looks more and more like a standard normal distribution.</p>
</section>
<section id="plotting" class="level3">
<h3 class="anchored" data-anchor-id="plotting">Plotting</h3>
<p>So let’s visualize this.</p>
<p>In this next step, I take the densities we calculated above, and put them together into a data frame, along with densities calculated from a normal distribution, for comparison.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>distplot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">values =</span> x_vals,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">normal =</span> <span class="fu">dnorm</span>(x_vals, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">t_01 =</span> t_01,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">t_02 =</span> t_02,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">t_04 =</span> t_04,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">t_10 =</span> t_10)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, I’ll use a handy function from the <code>tidyr</code> package in order to reshape the data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>distplot_long <span class="ot">&lt;-</span> <span class="fu">pivot_longer</span>(distplot_data, <span class="at">cols =</span> normal<span class="sc">:</span>t_10,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">values_to =</span> <span class="st">"density"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">names_to =</span> <span class="st">"distribution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we can use this reshaped data to plot the different curves in different colors. The normal distribution is plotted in black with a dashed line. As you can see, as the degrees of freedom parameter increases, it gets closer to a normal distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(distplot_long, <span class="fu">aes</span>(values, density)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color =</span> distribution, <span class="at">linetype =</span> distribution)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_linetype_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>, <span class="st">"orange"</span>, <span class="st">"blue"</span>, <span class="st">"purple"</span>)) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="R_t_distribution_confidence_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Neat!</p>
</section>
</section>
</section>
<section id="calculating-a-p-value-from-a-t-distribution" class="level1">
<h1>Calculating a <em>p</em> value from a <em>t</em> distribution</h1>
<section id="populations-and-samples" class="level2">
<h2 class="anchored" data-anchor-id="populations-and-samples">Populations and samples</h2>
<p>One of the main roles of the <em>t</em> distribution is as a <em>test statistic</em>, which means that the distribution holds under a certain null hypothesis. One original application was for evaluating whether two populations of values have different means, based on the means of two samples.</p>
<p>For example, take the father/son height data we’ve looked at throughout the course. We have a sample of fathers and a sample of (adult) sons, and normally we wouldn’t necessarily think of these as separate groups, since all fathers are also someone’s son. But these also represent different generations, so in that sense they could be from two different populations.</p>
<p>This raises a question: do these two generations of men differ in their average height? We are asking a question about the <em>populations</em> (the overall groups of men from these two generations), but we only have <em>samples</em> of data.</p>
<p>What Gosset showed was that if these two populations had exactly the same average height – a form of the <em>null hypothesis</em>, since the difference is hypothesized to be exactly zero – you could calculate a statistic that followed the distribution that we now call the <em>t</em> distribution. And if that <em>t</em> value was unexpectedly large (positive or negative), it would produce a small <em>p</em> value, indicating that the data would be surprising to find if the null hypothesis were true.</p>
<p>So let’s take an even smaller sample of data from the full data set, and go through the steps of calculating the <em>t</em> and <em>p</em> values for this kind of test. First, I will select a random sample of 30 rows of data from our full data set (representing 30 father-son pairs), and by using the <code>set.seed()</code> function, I can make sure that we pull the same 30 pairs each time we run this code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">33</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>father_son_sample <span class="ot">&lt;-</span> pl[<span class="fu">sample</span>(<span class="fu">nrow</span>(pl), <span class="dv">30</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, let’s compute the difference between the two. The following gets the pairwise differences and puts them in a new column. We can inspect the top few rows to check that we did this correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>father_son_sample<span class="sc">$</span>difference <span class="ot">&lt;-</span> father_son_sample<span class="sc">$</span>father_height <span class="sc">-</span> father_son_sample<span class="sc">$</span>son_height</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(father_son_sample)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     observation father_height son_height difference
1288        1288          67.5       66.5          1
2876        2876          66.5       69.5         -3
1138        1138          65.5       66.5         -1
4072        4072          70.5       72.5         -2
1017        1017          64.5       66.5         -2
688          688          65.5       65.5          0</code></pre>
</div>
</div>
</section>
<section id="computing-standard-errors-and-t-values" class="level2">
<h2 class="anchored" data-anchor-id="computing-standard-errors-and-t-values">Computing standard errors and <em>t</em> values</h2>
<p>Now all we need to compute the <em>t</em> test is to divide the mean difference by the standard error of the mean. The standard error of the mean difference is the standard <em>deviation</em> of the vector of differences, divided the square root of <span class="math inline">\(N\)</span>, the total number of difference values. In equation form, the standard error of the mean looks like this:</p>
<p><span class="math display">\[t = \frac{\sigma}{\sqrt{n}}\]</span></p>
<p>In order to capture this in R, we can just write out the code for these calculations. But this is a good opportunity to show you how to make your own functions in R. In the code below, we can create a new function definition. In this case, we decide that it will take an argument called <code>x</code>, and it simply performs the standard error calculation to return the result. We then show that this works on the column of height differences that we added to our data frame above. Finally, we can calculate the <em>t</em> value by dividing the mean of the differences by this standard error of the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define a function</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>std_err_mean <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">sd</span>(x)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(x)))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># use our new function</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>(std_err_differences <span class="ot">&lt;-</span> <span class="fu">std_err_mean</span>(father_son_sample<span class="sc">$</span>difference))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3895178</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate t</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>(t_diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(father_son_sample<span class="sc">$</span>difference)<span class="sc">/</span>std_err_differences)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.567277</code></pre>
</div>
</div>
<p>The result is a <em>t</em> value of -2.57 (rounding off to two decimals). The <em>t</em> distribution is symmetrical around zero, so the negative doesn’t really matter for our purposes. All it indicates is that the sons are on average taller than their fathers (rather than vice versa), since we subtracted the son heights from the father heights. If we had subtracted in the other direction, we would have ended up with a positive <em>t</em>, but the same value.</p>
</section>
<section id="testing-the-t" class="level2">
<h2 class="anchored" data-anchor-id="testing-the-t">Testing the <em>t</em></h2>
<p>The final step is to compute a <em>p</em>-value, which tells us how surprising this <em>t</em> value of -2.57 would be if the null hypothesis were true. How do we know if -2.57 is a surprising value? First, look up at the graph of the <em>t</em> distribution from earlier. Clearly -2.57 is in the left tail, so it’s fairly extreme. What we want is to know exactly how much of the <em>t</em> distribution would be as negative or more negative than this value, essentially the area under the curve to the left of -2.57. But in this kind of test, we also need to test the other side, how much of the distribution would be as high or higher than 2.57. This is also why the +/- sign doesn’t matter so much, because we almost always perform two-tailed tests, since we could have found out that the sons were taller or shorter than the fathers. What we care about is that whichever direction this difference is, it’s significantly different from zero, so that we can reject the null hypothesis.</p>
<p>We can use the <code>pt()</code> function in R, but we need one more piece of information: the degrees of freedom. This is because this is the one parameter of the <em>t</em> distribution. You can review the discussion from the Unit 5 reading, but in brief since we have one parameter in our analysis (the mean value we are testing), our degrees of freedom is the number of observations minus one (because there’s one parameter), so that’s 30 - 1 = 29.</p>
<p>Armed with a <em>t</em> and a degrees of freedom, we can now calculate how much of the distribution is at or lower than our <em>t</em> value of -2.57:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(<span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.57</span>, <span class="dv">29</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.007786343</code></pre>
</div>
</div>
<p>But recall that we also need the upper tail, so we can essentially multiply this by two in order to get the final <em>p</em>-value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>(p_value <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="sc">-</span><span class="fl">2.57</span>, <span class="dv">29</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01557269</code></pre>
</div>
</div>
<p>And since this <em>p</em>-value of around 0.016 is less than 0.05, we say that this difference is statistically significant, and we can reject the null hypothesis.</p>
<p>In other words, we can end up concluding that on average, we expect the average height of the younger generation to be taller than the older generation.</p>
</section>
<section id="regression-coefficient-tests" class="level2">
<h2 class="anchored" data-anchor-id="regression-coefficient-tests">Regression coefficient tests</h2>
<p>The process above is essentially the same when we test the signficance of regression coefficients. <a href="./R_regression_inference.html">A separate tutorial</a> shows you how to extract these values from an <code>lm</code> object in R, so you don’t need to do any of these calculations, but they work essentially the same way. The <em>t</em> is the result of the regression parameter (for example, a slope) divided by its standard error, and the degrees of freedom are determined as the number of observations minus the number of parameters. Once you have a <em>t</em> and a degrees of freedom, you can calculate the <em>p</em>-value just the same as we did here above.</p>
</section>
</section>
<section id="constructing-a-confidence-interval" class="level1 page-columns page-full">
<h1>Constructing a confidence interval</h1>
<p>The final step in this tutorial are to apply these same concepts in a slightly different way, in order to construct a confidence interval.</p>
<p>The first step is to decide on the <em>confidence level</em>. This is similar to setting an <em>alpha</em> threshold for what counts as a “significant” <em>p</em>-value threshold. The higher the “confidence”, the wider the interval will be. This makes intuitive sense if you think about it. Imagine that I was meeting a new person, and was asked to guess their height. If I made a guess with a large interval, like saying, “I think they will be between 50 and 80 inches tall,” I could be highly confident that they would fall in that range. Conversely, if I guessed a narrower range, like between 67 and 70 inches, I would have much less confidence that I would be correct.</p>
<p>Setting a confidence level is usually expressed as a percentile, and similar to how p &lt; 0.05 is a typical threshold for significance, it’s common to construct a 95% confidence interval. This is generally interpreted to mean that you can be 95% confident that the true value lies in this interval.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> You could construct 50% confidence intervals, or 99%, or 83%, or whatever you wanted. But 95% is the most typical choice.</p>
<div class="no-row-height column-margin column-container"><div id="fn2"><p><sup>2</sup>&nbsp;Technically, the proper frequentist definition is to say that if you were able to repeat this same data collection (with new samples) many, many times, and you constructed a confidence interval each time, 95% of the confidence intervals from these hypothetical data sets would include the “true” value of the parameter. But in practice we treat it as “close enough” to say that when we construct a single 95% confidence interval, we can have 95% confidence that the true values lies inside that interval.</p></div></div><p>The steps for constructing a confidence interval are as follows:</p>
<ol type="1">
<li>Obtain an estimate (which can be a mean, or a regression parameter, or whatever).</li>
<li>Obtain the standard error of that estimate.</li>
<li>Obtain “critical values” from the <em>t</em> distribution<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> for the high and low ends of the interval.</li>
<li>Multiply the critical <em>t</em> values by the standard error.</li>
<li>Add the results of step 4 (one should be negative and the other positive) to the mean, so you end up with an interval that goes both above and below the mean.</li>
</ol>
<div class="no-row-height column-margin column-container"><div id="fn3"><p><sup>3</sup>&nbsp;If you are constructing a confidence interval around a mean or a regression parameter (which are very common things to do), you definitely use a <em>t</em> distribution. But there are other times when you might use a normal or other distribution.</p></div></div><p>Let’s use these steps to construct a confidence interval around the height differences that we were just examining.</p>
<p>First, let’s re-compute the mean and standard error, just for illustration. We can re-use that new function we made above called <code>std_err_mean()</code> as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(mean_diff <span class="ot">&lt;-</span> <span class="fu">mean</span>(father_son_sample<span class="sc">$</span>difference))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(stderr_diff <span class="ot">&lt;-</span> <span class="fu">std_err_mean</span>(father_son_sample<span class="sc">$</span>difference))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3895178</code></pre>
</div>
</div>
<p>That takes care of steps 1 and 2, but for step 3, what is a “critical value”? Remember how as the <em>t</em> gets larger, the <em>p</em> value gets smaller, and at some point we would cross the <em>p</em> &lt; 0.05 threshold? The “critical value” is the value of <em>t</em> that corresponds to the target <em>p</em> value. When we have a 95% confidence interval, this means we are trying to cover the middle 95% of the data. This in turn means that the boundaries of our interval are at the 2.5% and 97.5% levels of the distribution. To put it another way, if we want the middle 95% of the distribution, what we’re left with is 2.5% of the data at the bottom and at the top of the distribution.</p>
<p>The following code makes use of the <code>qt()</code> function,<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> so that we can give it these % levels and it will give us back the corresponding critical <em>t</em> values. Again, we need to provide the degrees of freedom parameter for the <em>t</em>, and again, it’s the number of observations minus the number of parameters. Here we are just looking at the mean, so it’s 30 - 1 = 29 once more. The code below shows us that for 29 degrees of freedom, the critical <em>t</em> values are -2.045 and 2.045.</p>
<div class="no-row-height column-margin column-container"><div id="fn4"><p><sup>4</sup>&nbsp;At this point we have now seen the full “family” of distribution functions. the <code>r</code> version, like <code>rnorm()</code> or <code>runif()</code> or <code>rt()</code> generates random numbers from that distribution. The <code>d</code> function, like <code>dnorm()</code> or <code>dt()</code> takes values from the distribution and returns the probability density for each. The <code>p</code> function, like <code>pnorm()</code> or <code>pt()</code>, takes values from the distribution and returns the cumulative probability density (aka, “how much of the distribution is equal to or less than this value?”). And now finally the <code>q</code> function, like <code>qnorm()</code> or <code>qt()</code>, is the reverse, taking <em>p</em>-values, which you can also think of as quantiles, and returning the critical values at those points in the distribution.</p></div></div><div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(high_low <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>), <span class="at">df =</span> <span class="dv">29</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.04523  2.04523</code></pre>
</div>
</div>
<p>Now, all we need to do is multiply these critical <em>t</em> values by our standard error, and add them both to the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(confint_95 <span class="ot">&lt;-</span> (high_low <span class="sc">*</span> stderr_diff) <span class="sc">+</span> mean_diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -1.7966534 -0.2033466</code></pre>
</div>
</div>
<p>This tells us that while the mean difference in this small sample of 30 father-son pairs is -1 (meaning that fathers are on average 1 inch shorter than their sons), the 95% confidence interval is between -1.80 and -0.20 inches. This means that since we only have 30 pairs here, we have some uncertainty about whether the overall difference in the larger population is exactly -1, but we can still be 95% confident that the overall difference will fall between -1.80 and -0.20.</p>
<p>If we wanted to be 99% confident, we would need to compute different critical <em>t</em> values, with the following results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>(higher_lower <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.005</span>, <span class="fl">0.995</span>), <span class="at">df =</span> <span class="dv">29</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.756386  2.756386</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>(confint_99 <span class="ot">&lt;-</span> (higher_lower <span class="sc">*</span> stderr_diff) <span class="sc">+</span> mean_diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.07366145  0.07366145</code></pre>
</div>
</div>
<p>At this point, our interval stretches from -2.07 inches to <em>positive</em> 0.07 inches. So at this point, we can’t quite be 99% confident that fathers in the larger population are shorter than their sons on average. But we can say that if they aren’t shorter, they almost certainly are not much taller, and they are possibly up to 2 inches shorter.</p>
<p>With larger samples of data, the standard error will typically shrink, so the confidence interval will also usually get narrower. The only time adding data may not reduce your uncertainty is if the new data is very different or much more variable than the previous data.</p>
<section id="confidence-intervals-for-regression-parameters" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-for-regression-parameters">Confidence intervals for regression parameters</h2>
<p>This process actually works exactly the same for regression parameters; all the same steps. You just need to make sure you’re getting the right degrees of freedom, but that’s still just the number of observations minus the number of parameters. So if you have a more complex model with 2000 observations and 20 parameters, you’d still have 1980 degrees of freedom.</p>
<p>Otherwise, as long as you get the estimates and standard errors for the parameter, you can easily follow the steps here to compute a confidence interval, and you can pick any confidence level you want, just by changing the critical <em>t</em> values.</p>
</section>
<section id="other-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="other-confidence-intervals">Other confidence intervals</h2>
<p>In fact, this process is so general, it applies nearly the same for virtually any other distribution. Usually, the only thing that might change is how the standard errors are calculated. For example, if your data is a proportion instead of a mean – imagine a poll result with 53% of the vote going to a particular candidate – you could calculate a confidence interval around that estimate, but the formula for the standard error of a proportion is different so you would need to apply that.</p>
<p>But again, if you have an estimate and a standard error, you can get a confidence interval.</p>
</section>
<section id="quick-and-dirty-confidence" class="level2">
<h2 class="anchored" data-anchor-id="quick-and-dirty-confidence">Quick and dirty confidence</h2>
<p>Finally, I should point out that while getting these exact calculations is important if you want to have a confidence interval that is precisely 95% or whatever you pick, you may have noticed that a lot of the critical values are hovering around 2. It turns out that if you just take +/- 2 standard errors around the mean, that is a quick approximation to a 95% confidence interval. If you take +/- 1 standard error, that’s roughly a 68% confidence interval. Remember that the “confidence” refers to the confidence that the “true” or population value is within the interval. If you have a wider interval, you can be more confident that the true value is contained in that interval.</p>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<p>There are many functions in R that will calculate some of these quantities for you, depending on what kind of analysis you are performing or what kind of data you have. For example the summary output for linear models in R automatically computes standard errors, <em>t</em> values, and <em>p</em>-values. But the ability to compute these yourself can come in handy, and this is especially true with confidence intervals.</p>
<p>In fact, the ease of constructing confidence intervals should further encourage you to examine these often. And if a quick-and-dirty method of +/- 2 standard errors around the mean is a pretty good approximation of 95% confidence, there’s almost no excuse not to try to use them more, as a way to help you think about the uncertainty in your estimates.</p>
<p>Embrace uncertainty, and work to understand it!</p>


</section>


</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>